'use client';
import {useEffect,useState,useCallback} from 'react';
import {PushButton} from '@/components/push-button';
import {clock,money,shopToday} from '@/lib/booking-data';
type Barber={id:string;name:string;slug:string};
type Booking={id:string;group_id:string;barber_id:string;start_minute:number;duration:number;status:string;price_pence:number;fee_pence:number;fee_status:string;updated_at:string;late_minutes:number;barbers:{name:string};services:{name:string};booking_groups:{customers:{name:string;email:string;phone:string;preferences:string}}};
type Diary={staff:{role:string;barber_id:string};bookings:Booking[];barbers:Barber[];services:{id:string;slug:string;name:string}[];blocks:{id:string;barber_id:string;start_minute:number;duration:number;label:string}[];events:{id:string;kind:string;created_at:string}[]};
type Report={period:string;trims:number;completed:number;noShows:number;cancelled:number;completedValue:number;fees:number};
async function api(url:string,data?:unknown){const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not complete this action');return j;}
export function Diary(){
 const [date,setDate]=useState(shopToday()),[diary,setDiary]=useState<Diary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[report,setReport]=useState<Report|null>(null),[tab,setTab]=useState('diary');
 const load=useCallback(async()=>{try{setDiary(await api('/api/staff/diary?date='+date));setError('');}catch(e){setError((e as Error).message);}},[date]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);const interval=setInterval(()=>void load(),60000);return()=>{clearTimeout(t);clearInterval(interval);};},[load]);
 async function act(url:string,data:unknown){setBusy(true);setError('');try{await api(url,data);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!diary)return <section className="staff-content"><h1>your day.</h1><p>Sign in to your chair.</p><form className="details-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('/api/staff/session',{email:f.get('email'),password:f.get('password')});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>email<input required type="email" name="email" autoComplete="username"/></label><label>password<input required type="password" name="password" autoComplete="current-password"/></label><button disabled={busy}>sign in</button></form>{error&&<p role="alert">{error}</p>}</section>;
 const visible=diary.barbers.filter(b=>diary.staff.role==='owner'||b.id===diary.staff.barber_id);
 return <section className="staff-content"><div className="staff-toolbar"><h1>your day.</h1><button onClick={async()=>{await fetch('/api/staff/session',{method:'DELETE'});setDiary(null);}}>sign out</button></div><PushButton/><div className="staff-tabs">{['diary','walk-in','breaks','reports',...(diary.staff.role==='owner'?['settings','launch checks']:[])].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);if(t==='reports')api('/api/staff/reports').then(setReport).catch(e=>setError(e.message));}}>{t}</button>)}</div><label className="diary-date">date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<p className="error-message" role="alert">{error}</p>}
 {tab==='diary'&&<div className="diary-columns">{visible.map(barber=><div key={barber.id}><h2>{barber.name}.</h2>{diary.bookings.filter(b=>b.barber_id===barber.id).map(b=><article className="diary-trim" key={b.id}><strong>{clock(b.start_minute)} · {b.booking_groups.customers.name}</strong><p>{b.services.name} · {b.duration} min · £{money(b.price_pence/100)}</p><p className="booking-status">{b.status.replace('_',' ')}{b.late_minutes>0?` · running ${b.late_minutes} min late`:''}</p>{b.booking_groups.customers.preferences&&<p>{b.booking_groups.customers.preferences}</p>}<p><a href={'tel:'+b.booking_groups.customers.phone}>{b.booking_groups.customers.phone}</a></p>{['booked','arrived'].includes(b.status)&&<><div className="manage-links">{['arrived','done','no_show','cancelled'].filter(s=>s!==b.status).map(status=><button disabled={busy} key={status} onClick={()=>{if(['no_show','cancelled'].includes(status)&&!confirm(`Mark this trim ${status.replace('_',' ')}?`))return;void act('/api/staff/diary',{action:'status',id:b.id,status,version:b.updated_at});}}>{status.replace('_',' ')}</button>)}</div><details><summary>move trim</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const [h,m]=String(f.get('time')).split(':').map(Number);void act('/api/staff/diary',{action:'move',id:b.id,date:f.get('date'),time:h*60+m,version:b.updated_at});}}><input aria-label="New date" name="date" type="date" required defaultValue={date}/><input aria-label="New time" name="time" type="time" step="900" required defaultValue={clock(b.start_minute)}/><button disabled={busy}>save move</button></form></details></>}{b.fee_pence>0&&<p>Fee: £{money(b.fee_pence/100)} · {b.fee_status}</p>}{diary.staff.role==='owner'&&['review','charging'].includes(b.fee_status)&&<div className="manage-links"><button disabled={busy} onClick={()=>{if(confirm(`Charge the authorised £${money(b.fee_pence/100)} fee to this customer's saved card?`))void act('/api/staff/charge',{action:'charge',id:b.id});}}>charge fee</button>{b.fee_status==='review'&&<button disabled={busy} onClick={()=>void act('/api/staff/charge',{action:'waive',id:b.id})}>waive</button>}</div>}</article>)}{!diary.bookings.some(b=>b.barber_id===barber.id)&&<p>No trims booked.</p>}{diary.blocks.filter(b=>b.barber_id===barber.id).map(b=><article className="diary-block" key={b.id}>{clock(b.start_minute)} — {clock(b.start_minute+b.duration)} · {b.label}<button disabled={busy} onClick={()=>void act('/api/staff/diary',{action:'unblock',id:b.id})}>remove block</button></article>)}</div>)}</div>}
 {tab==='walk-in'&&<form className="details-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const [h,m]=String(f.get('time')).split(':').map(Number);void act('/api/staff/diary',{action:'walkin',date,time:h*60+m,name:f.get('name'),email:f.get('email'),phone:f.get('phone'),barber:f.get('barber'),service:f.get('service')});}}><h2>add a trim.</h2><label>customer<input name="name" required minLength={2}/></label><label>email (optional)<input type="email" name="email"/></label><label>mobile (optional)<input type="tel" name="phone"/></label><label>barber<select name="barber">{visible.map(b=><option value={b.slug} key={b.id}>{b.name}</option>)}</select></label><label>service<select name="service">{diary.services.map(s=><option value={s.slug} key={s.id}>{s.name}</option>)}</select></label><label>time<input type="time" step="900" name="time" required/></label><button disabled={busy}>add to diary</button></form>}
 {tab==='breaks'&&<form className="details-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const [h,m]=String(f.get('time')).split(':').map(Number);void act('/api/staff/diary',{action:'block',date,time:h*60+m,barber:f.get('barber'),duration:Number(f.get('duration')),label:f.get('label')});}}><h2>make some space.</h2><p>Add a break or block the whole day for a holiday. Existing bookings must be moved first.</p><label>barber<select name="barber">{visible.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>label<input name="label" required defaultValue="break"/></label><label>from<input type="time" step="900" name="time" required defaultValue="00:00"/></label><label>minutes<input type="number" name="duration" min="5" max="1440" defaultValue="1440" required/></label><button disabled={busy}>block time</button></form>}
 {tab==='reports'&&report&&<><h2>{report.period}.</h2><div className="report-grid">{[['Completed trims',report.completed],['Completed service value',`£${money(report.completedValue/100)}`],['No-shows',report.noShows],['Cancellations',report.cancelled],['Collected fees',`£${money(report.fees/100)}`]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p>Service value is based on completed trims; it is not a payment reconciliation.</p></>}
 {tab==='launch checks'&&<Readiness/>}
 {tab==='settings'&&<Settings diary={diary} act={act} busy={busy}/>}
 </section>;
}
function Settings({diary,act,busy}:{diary:Diary;act:(url:string,data:unknown)=>Promise<void>;busy:boolean}){
 const [policy,setPolicy]=useState<{cancellation_hours:number;late_percent:number;no_show_percent:number;policy_confirmed:boolean}|null>(null);
 const [loadError,setLoadError]=useState('');
 useEffect(()=>{api('/api/staff/settings').then(d=>setPolicy(d.policy)).catch(e=>setLoadError(e.message));},[]);
 if(!policy)return <p role="status">{loadError||'Loading settings…'}</p>;
 return <div className="settings-grid"><form className="details-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/staff/settings',{action:'policy',cancellation_hours:Number(f.get('hours')),late_percent:Number(f.get('late')),no_show_percent:Number(f.get('noShow')),policy_confirmed:f.get('confirmed')==='on'});}}><h2>cancellation policy.</h2><p>Changes apply to new bookings. Existing bookings keep the policy accepted at checkout.</p><label>free cancellation notice (hours)<input name="hours" type="number" min="0" max="168" defaultValue={policy.cancellation_hours}/></label><label>late cancellation (%)<input name="late" type="number" min="0" max="100" defaultValue={policy.late_percent}/></label><label>no-show (%)<input name="noShow" type="number" min="0" max="100" defaultValue={policy.no_show_percent}/></label><label><input type="checkbox" name="confirmed" defaultChecked={policy.policy_confirmed}/> I confirm this is the shop’s policy</label><button disabled={busy}>save policy</button></form><form className="details-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/staff/settings',{action:'price',barber_id:f.get('barber'),service_id:f.get('service'),price_pence:Math.round(Number(f.get('price'))*100),duration:Number(f.get('duration'))});}}><h2>prices & timings.</h2><label>barber<select name="barber">{diary.barbers.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>service<select name="service">{diary.services.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>price (£)<input name="price" type="number" step="0.01" min="0" required/></label><label>duration (minutes)<input name="duration" type="number" min="5" max="480" required/></label><button disabled={busy}>save price</button></form><form className="details-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const minute=(v:FormDataEntryValue|null)=>{if(!v)return null;const [h,m]=String(v).split(':').map(Number);return h*60+m;};void act('/api/staff/settings',{action:'schedule',barber_id:f.get('barber'),iso_weekday:Number(f.get('day')),open_minute:minute(f.get('open')),close_minute:minute(f.get('close'))});}}><h2>weekly hours.</h2><label>barber<select name="barber">{diary.barbers.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>day<select name="day">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label>start (blank for day off)<input name="open" type="time"/></label><label>finish<input name="close" type="time"/></label><button disabled={busy}>save working hours</button></form></div>}

function Readiness(){
 const [data,setData]=useState<{checks:{label:string;ready:boolean}[];jobs:{id:string;kind:string;channel:string;status:string;due_at:string;last_error:string|null}[];note:string}|null>(null);
 const [error,setError]=useState('');
 useEffect(()=>{api('/api/staff/readiness').then(setData).catch(e=>setError(e.message));},[]);
 if(!data)return <p role="status">{error||'Checking setup…'}</p>;
 return <div><h2>ready for launch?</h2><p>{data.note}</p><ul>{data.checks.map(c=><li key={c.label}>{c.ready?'✓':'○'} {c.label}</li>)}</ul><h2>message queue.</h2>{!data.jobs.length?<p>No pending or failed messages.</p>:data.jobs.map(j=><article className="diary-trim" key={j.id}><strong>{j.kind.replaceAll('_',' ')} · {j.channel}</strong><p>{j.status} · due {new Date(j.due_at).toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>{j.last_error&&<p>{j.last_error}</p>}</article>)}<p>Check failed deliveries against the provider record before retrying. This list shows the oldest 50 unsettled messages.</p></div>;
}
